# TTY behaviour

stty -ixon

# Bash behaviour

shopt -s \
  checkhash \
  histreedit \
  histappend

[ $BASH_VERSINFO -ge 4 ] && shopt -s \
    autocd \
    globstar

# Colors

export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad
export GREP_OPTIONS=--color

# Prompt

PROMPT_COMMAND=echo
if [ -n $BREW_PREFIX ]; then
  if [ -f $BREW_PREFIX/share/liquidprompt ]; then
    . $BREW_PREFIX/share/liquidprompt
  fi
fi

# GTK

if [ -n $BREW_PREFIX ]; then
  if [ -d $BREW_PREFIX/lib/gtk-2.0 ]; then
    export GTK_PATH=$BREW_PREFIX/lib/gtk-2.0
  fi
fi

# Completions

if [ -n $BREW_PREFIX ]; then
  if [ $BASH_VERSINFO -ge 4 ] \
      && [ -f $BREW_PREFIX/share/bash-completion/bash_completion ]; then
    . $BREW_PREFIX/share/bash-completion/bash_completion
  elif [ -f $BREW_PREFIX/etc/bash_completion ]; then
    . $BREW_PREFIX/etc/bash_completion
  fi
  [ -f $BREW_PREFIX/etc/profile.d/z.sh ] && . $BREW_PREFIX/etc/profile.d/z.sh
fi

. <(npm completion 2>/dev/null)

# Aliases

[ -f ~/.aliasrc ] && . ~/.aliasrc
