# Environment

if [ -d /Applications/Xcode.app/Developer/usr/bin ]; then
  export PATH=/Applications/Xcode.app/Developer/usr/bin:$PATH
fi

export HISTCONTROL=ignorespace:erasedups
export HISTSIZE=2000

export BREW_PREFIX=`brew --prefix 2>/dev/null`

if [ -n $BREW_PREFIX ]; then
  export PATH=$BREW_PREFIX/bin:$BREW_PREFIX/sbin:$PATH

  if [ -n "`brew --prefix ruby 2>/dev/null`" ]; then
    export GEM_HOME=`brew --prefix ruby`
    export PATH=`brew --prefix ruby`/bin:$PATH
  fi
fi

[ -d ~/bin ] && export PATH=~/bin:$PATH

[ -d ~/.cabal ] && export PATH=~/.cabal/bin:$PATH

# Source non login initialisation file

[ -f ~/.bashrc ] && . ~/.bashrc
